### ISSUE TITLE
KeyError: 'phone_ids'

### ISSUE THREAD

**Issue by baiyutang** [SCUTlihaoyu/open-chat-video-editor#21]
```
2023-05-23 07:01:21,517 - comm.mylog - INFO - chatgpt response: Here's a 50-word short video copy using cat content:

"Watch our cute cat playing with a string, trying to catch it and make it fly. Look how excited it is, just like a child playing with a toy. Don't you feel like hugging it and petting its head? Look at its little claws, they're so sharp and fierce. Sure, it's just a cat, but it's our pet and we love it just the same. Watch and enjoy our cat video."
2023-05-23 07:01:21,517 - comm.mylog - INFO - sentences: ['Here\'s a 50-word short video copy using cat content:"Watch our cute cat playing with a string', ' trying to catch it and make it fly', ' Look how excited it is', ' just like a child playing with a toy', " Don't you feel like hugging it and petting its head", ' Look at its little claws', " they're so sharp and fierce", ' Sure', " it's just a cat", " but it's our pet and we love it just the same", ' Watch and enjoy our cat video', '"']
2023-05-23 07:01:21,517 - comm.mylog - INFO - en_out_text: ['Here\'s a 50-word short video copy using cat content:"Watch our cute cat playing with a string', ' trying to catch it and make it fly', ' Look how excited it is', ' just like a child playing with a toy', " Don't you feel like hugging it and petting its head", ' Look at its little claws', " they're so sharp and fierce", ' Sure', " it's just a cat", " but it's our pet and we love it just the same", ' Watch and enjoy our cat video', '"']
Traceback (most recent call last):
  File "/data/anaconda3/envs/open_editor/lib/python3.8/site-packages/gradio/routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "/data/anaconda3/envs/open_editor/lib/python3.8/site-packages/gradio/blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "/data/anaconda3/envs/open_editor/lib/python3.8/site-packages/gradio/blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/data/anaconda3/envs/open_editor/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/data/anaconda3/envs/open_editor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/data/anaconda3/envs/open_editor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "app/app.py", line 30, in run_Text2VideoEditor_logit
    out_text,video_out = editor.run(input_text,style_text,out_video)
  File "/opt/gf/open-chat-video-editor/editor/chat_editor.py", line 50, in run
    tts_resp = self.audio_generator.batch_run(tts_in_text)
  File "/opt/gf/open-chat-video-editor/generator/tts/tts_generator.py", line 27, in batch_run
    resp.append(self.run_tts(text))
  File "/opt/gf/open-chat-video-editor/generator/tts/tts_generator.py", line 15, in run_tts
    self.tts_model.run_tts(text,out_path)
  File "/opt/gf/open-chat-video-editor/generator/tts/paddlespeech_model.py", line 16, in run_tts
    self.tts(text=text,lang=self.lang,am=self.am,output=out_path)
  File "/data/anaconda3/envs/open_editor/lib/python3.8/site-packages/paddlespeech/cli/utils.py", line 328, in _warpper
    return executor_func(self, *args, **kwargs)
  File "/data/anaconda3/envs/open_editor/lib/python3.8/site-packages/paddlespeech/cli/tts/infer.py", line 710, in __call__
    self.infer(text=text, lang=lang, am=am, spk_id=spk_id)
  File "<decorator-gen-603>", line 2, in infer
  File "/data/anaconda3/envs/open_editor/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 375, in _decorate_function
    return func(*args, **kwargs)
  File "/data/anaconda3/envs/open_editor/lib/python3.8/site-packages/paddlespeech/cli/tts/infer.py", line 471, in infer
    frontend_dict = run_frontend(
  File "/data/anaconda3/envs/open_editor/lib/python3.8/site-packages/paddlespeech/t2s/exps/syn_utils.py", line 305, in run_frontend
    phone_ids = input_ids["phone_ids"]
KeyError: 'phone_ids'
```

**Comment by baiyutang** [comment]
I remembered  had selected one.

**Comment by jeffzhengye** [comment]
this is due to the tts you used only support chinese and limitted of english.
